"""initial schema

Revision ID: be0bbd4da6d5
Revises: 
Create Date: 2026-02-24 09:31:43.680122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0bbd4da6d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fit_bounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_type', sa.String(length=20), nullable=False),
    sa.Column('param_name', sa.String(length=50), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hold_type', 'param_name')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pao2_0', sa.Float(), nullable=False),
    sa.Column('pvo2', sa.Float(), nullable=False),
    sa.Column('tau_washout', sa.Float(), nullable=False),
    sa.Column('p50_base', sa.Float(), nullable=False),
    sa.Column('n', sa.Float(), nullable=False),
    sa.Column('bohr_coeff', sa.Float(), nullable=False),
    sa.Column('lag', sa.Float(), nullable=False),
    sa.Column('r_offset', sa.Float(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('objective_val', sa.Float(), nullable=False),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.Column('n_holds_used', sa.Integer(), nullable=False),
    sa.Column('hold_ids_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hold_type', 'version')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('csv_filename', sa.String(length=500), nullable=False),
    sa.Column('csv_blob', sa.LargeBinary(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('hold_number', sa.Integer(), nullable=False),
    sa.Column('hold_type', sa.String(length=20), nullable=False),
    sa.Column('start_time_s', sa.Integer(), nullable=False),
    sa.Column('end_time_s', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('min_spo2', sa.Float(), nullable=True),
    sa.Column('min_hr', sa.Float(), nullable=True),
    sa.Column('include_in_fit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'hold_number')
    )
    op.create_table('hold_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_s', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hold_id'], ['holds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hold_id', 'elapsed_s')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hold_data')
    op.drop_table('holds')
    op.drop_table('sessions')
    op.drop_table('model_versions')
    op.drop_table('fit_bounds')
    # ### end Alembic commands ###
